-- AlterTable
ALTER TABLE `car` ADD COLUMN `isRegistered` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `color` VARCHAR(191) NULL DEFAULT 'red';

-- AlterTable
ALTER TABLE `civil` ADD COLUMN `dateOfBirth` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `description` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `eyes` VARCHAR(191) NOT NULL DEFAULT 'black',
    ADD COLUMN `hair` VARCHAR(191) NOT NULL DEFAULT 'black',
    ADD COLUMN `phoneNumber` INTEGER NOT NULL DEFAULT 2124233234,
    ADD COLUMN `race` VARCHAR(191) NOT NULL DEFAULT 'white',
    ADD COLUMN `sex` VARCHAR(191) NOT NULL DEFAULT 'man';
